### ISSUE TITLE
panic on Win10 because net.Addr is *net.IPNet, not *net.IPAddr (includes fix)

### ISSUE THREAD

**Issue by sybrenstuvel** [fromkeith/gossdp#6]
This panic happens on Windows 10 Professional, using Go 1.9:

>  panic: interface conversion: net.Addr is *net.IPNet, not *net.IPAddr

This is how I start the SSDP server:

```
func startSSDPServer() *gossdp.Ssdp {
	ssdp, err := gossdp.NewSsdp(nil)
	if err != nil {
		log.Errorln("Error creating ssdp server: ", err)
		return nil
	}

	log.Info("Starting UPnP/SSDP advertisement")

	// This will block until stop is called. so open it in a goroutine here
	go func() {
		ssdp.Start()
		log.Info("Shut down UPnP/SSDP advertisement")
	}()

	// Define the service we want to advertise
	serverDef := gossdp.AdvertisableServer{
		ServiceType: "urn:service:name:0", // define the service type
		DeviceUuid:  config.SSDPDeviceUUID,    // make this unique!
		Location:    config.OwnURL,            // this is the location of the service we are advertising
		MaxAge:      3600,                     // Max age this advertisment is valid for
	}
	ssdp.AdvertiseServer(serverDef)

	return ssdp
}
```

I've fixed this in my fork: https://github.com/armadillica/gossdp/commit/2c56973e2c79e0a20e46bc6222a2a88aad79f26a

I can create a pull request for this, but that'll also include another commit, which applies "go fmt" to all source files. I think that's a good idea to include as well, but it's out of scope for this issue report.

**Comment by fromkeith** [comment]
Thanks!

I pushed two changes.
1. `go fmt`
2. Using a slightly modified version of your type casting.

Let me know if you run into any issues, I only did a quick test of the change.
